### PR TITLE
added hamburger menu to replace navbar for smaller screens, fixed scroll bounce glitch

### LINKED ISSUE #47: Navigation Bar responsiveness and background
Currently, the navigation bar is not responsive to smaller devices like phones and glitches when scrolling different pages.

Iphone 12 pro:
image

### PR DESCRIPTION
**Pull request by alognz**
closes #47 
Screenshot 2024-12-09 at 2 39 29 PM
Screenshot 2024-12-09 at 2 40 05 PM

### CODE REVIEW

File: src/components/stickyNavBar.js [hunk 1]
```diff
@@ -1,21 +1,45 @@
...
     <>
-      <div className="navbar-wrapper">
+      <div style={{ height: isScrolled ? '70px' : '0' }}></div>
+      <div className={`navbar-wrapper ${isScrolled ? 'fixed-top' : ''}`}>
         <div className="navbar">
-          <Link to="/Home" className="button">Home</Link>
-          <Link to="/About" className="button">About Us</Link>
-          <Link to="/Calendar" className="button">Calendar</Link>
-          <Link to="/Get-Involved" className="button">Get Involved</Link>
+          <button className="hamburger-menu" onClick={toggleMenu}>
```
Comment (scuruchima1) [inline src/components/stickyNavBar.js]: Could we add a way to unfocus the hamburger menu, so that if a mobile user clicks off the menu it closes?

File: src/components/stickyNavBar.js [hunk 2]
```diff
@@ -1,21 +1,45 @@
...
+            <span className="line"></span>
+            <span className="line"></span>
+            <span className="line"></span>
+          </button>
+          <div className={`nav-links ${menuOpen ? 'show' : ''}`}>
+            <Link to="/Home" className="button">Home</Link>
```
Comment (scuruchima1) [inline src/components/stickyNavBar.js]: When we click the button for the page that we are currently on, the menu does not go away either. I wonder if we could add an on click handler that toggle the menu off here.

File: src/styles/stickyNavBar.css [hunk 3]
```diff
@@ -1,34 +1,134 @@
...
+  animation: slide-in-right 0.3s forwards;
+}
+
+@keyframes slide-in-right {
+  to {
+    transform: translateX(0); 
+  }
+}
+
+@media (max-width: 500px) {
```
Comment (scuruchima1) [inline src/styles/stickyNavBar.css]: Some of the text appears to off center when viewed on a smaller phone such as the iPhone SE, after the hamburger menu is opened.

File: src/components/stickyNavBar.js (hunk 1 above)
Comment (boldenj2) [reply src/components/stickyNavBar.js]: +1

File: src/components/stickyNavBar.js (hunk 2 above)
Comment (boldenj2) [reply src/components/stickyNavBar.js]: +1

**Review by boldenj2 — CHANGES_REQUESTED** [review]

**Review by boldenj2 — APPROVED** [review]
lgtm

**Review by scuruchima1 — APPROVED** [review]
looks good to me!
